description "sixcoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env sixcoind_BIN="/usr/bin/sixcoind"
env sixcoind_USER="sixcoin"
env sixcoind_GROUP="sixcoin"
env sixcoind_PIDDIR="/var/run/sixcoind"
# upstart can't handle variables constructed with other variables
env sixcoind_PIDFILE="/var/run/sixcoind/sixcoind.pid"
env sixcoind_CONFIGFILE="/etc/sixcoin/sixcoin.conf"
env sixcoind_DATADIR="/var/lib/sixcoind"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # sixcoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$sixcoind_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run sixcoind."
        echo "The setting must appear in $sixcoind_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"sixcoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$sixcoind_PIDDIR"
    chmod 0755 "$sixcoind_PIDDIR"
    chown $sixcoind_USER:$sixcoind_GROUP "$sixcoind_PIDDIR"
    chown $sixcoind_USER:$sixcoind_GROUP "$sixcoind_CONFIGFILE"
    chmod 0660 "$sixcoind_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$sixcoind_PIDFILE" \
    --chuid $sixcoind_USER:$sixcoind_GROUP \
    --exec "$sixcoind_BIN" \
    -- \
    -pid="$sixcoind_PIDFILE" \
    -conf="$sixcoind_CONFIGFILE" \
    -datadir="$sixcoind_DATADIR" \
    -disablewallet \
    -daemon

