#!/bin/bash
#
#  sixcoind The sixcoin core server.
#
#
# chkconfig: 345 80 20
# description: sixcoind
# processname: sixcoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/sixcoind, see below
if [ -f /etc/sysconfig/sixcoind ]; then
        . /etc/sysconfig/sixcoind
fi

RETVAL=0

prog=sixcoind
# you can override the lockfile via sixcoind_LOCKFILE in /etc/sysconfig/sixcoind
lockfile=${sixcoind_LOCKFILE-/var/lock/subsys/sixcoind}

# sixcoind defaults to /usr/bin/sixcoind, override with sixcoind_BIN
sixcoind=${sixcoind_BIN-/usr/bin/sixcoind}

# sixcoind opts default to -disablewallet, override with sixcoind_OPTS
sixcoind_opts=${sixcoind_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $sixcoind $sixcoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
